### PR TITLE
Refactoring and Upgrading to .net 5.0

### PR DESCRIPTION
**Pull request by mahmmoudkinawy**
Hello there Can I Contribute on this project I'm gonna Upgrade it to .net 6.0 and Refactor Some Issues, I made a very little Refactoring, Just take a look please.

### CODE REVIEW

**Review by AhsanRazaUK — APPROVED** [review]

**Review by AhsanRazaUK — APPROVED** [review]

**Comment by mahmmoudkinawy** [comment]
Excuse me, Are you gonna merge them?

**Comment by mahmmoudkinawy** [comment]
Hello sir, can I contribute this API with you? And if everything is OK ...
Merge them with master branch?

**Comment by mahmmoudkinawy** [comment]
Yes, still in progress

**Review by AhsanRazaUK — APPROVED** [review]

**Comment by evgomes** [comment]
Hi @mahmmoudkinawy,

Everything looks good, I will merge this pull request. Thank you for your contribution.

Thank you @AhsanRazaUK for reviewing it too.

I will update the Readme with the changes list later.

**Comment by evgomes** [comment]
@all-contributors please add @mahmmoudkinawy for code

**Comment by evgomes** [comment]
@all-contributors please add @AhsanRazaUK for review

**Pull request merged**
